language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: stable
    - rust: beta
before_script:
  - rustup component add rust-src
script:
  - cargo build --verbose --all
