[package]
name = "rust-os"
version = "1.0.0"
authors = ["jerred"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"
rlibc = "1.0.0"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
