[package]
name = "rust-os"
version = "1.0.0"
authors = ["jerred"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
rlibc = "1.0.0"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
